services:
  bfmap:
    container_name: bfmap
    restart: unless-stopped
    environment:
      NODE_ENV: "production"
    image: ghcr.io/samokopecky/gym-map:main
    command:
      - "serve"
      - "-l"
      - "3000"
      - "-s"
      - "dist/"
  bfmapbe:
    container_name: bfmapbe
    restart: unless-stopped
    expose:
      - "5000"
    env_file: ./.env
    image: ghcr.io/samokopecky/gym-map-backend:main
    # depends_on:
    #   postgresql:
    #     condition: service_started
    volumes:
      - '/home/debian/app/media/gym-map:/media'
    command:
      - /bin/bash
      - -c
      - |
        ./wait-for.sh -t 10 db:5432 -- echo "wait-for: Postgres DB is ready"
        /app/gym-map --debug
