---
- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: Set default policy to deny incoming
  ufw:
    direction: incoming
    policy: deny

- name: Set default policy to allow outgoing
  ufw:
    direction: outgoing
    policy: allow

- name: Allow specific ports
  ufw:
    rule: allow
    port: "{{ item }}"
  loop: "{{ ufw_allowed_ports }}"

- name: Enable UFW
  ufw:
    state: enabled
    logging: 'on'
  notify: restart ufw

