---
- name: Git checkout infra repo
  ansible.builtin.git:
    repo: 'https://github.com/SamoKopecky/gym-map-infra'
    dest: $HOME/gym-map-infra


- name: Run `docker compose up`
  community.docker.docker_compose_v2:
    project_src: gym-map-infra/app
  register: output
